### ISSUE TITLE
The spinning icon is still showed when a request is canceled

### ISSUE THREAD

**Issue by synw** [nvms/wingman#15]
The spinning icon that is showed when the streaming response has not started does not disappear when a request is canceled. We must click clear conversation to remove it. It would be better if that icon could be hided on request cancel

**Comment by nvms** [comment]
Thanks for catching this -- fixed in 1.3.15.

A `This request was aborted` message is now also appended to the conversation window.

**Comment by synw** [comment]
Good. Just a remark: the "Bc: The operation was aborted." notification is not necessary, we already have the message. As it requires an action to close the notification it is annoying

**Comment by nvms** [comment]
Yeah, that's a good point. This no longer appears in 1.3.16.
