### ISSUE TITLE
Write function comment prompt: ask before injecting the response into the file

### ISSUE THREAD

**Issue by synw** [nvms/wingman#19]
I am using a very small local 3B model that does not follow the prompt instructions very well sometimes. For example using the "Write function comment" prompt it still outputs the body of the function despite the instruction not to included in the prompt:

![comments](https://github.com/nvms/wingman/assets/12034394/ef56bb16-30e4-4eec-97db-511225b9f515)

So in the end the body of the function is reinjected in the file. I suggest an option to ask before modifying files, in case of wrong model output. In the example above the output is of the wrong format but is semantically correct, so I can just copy the comments into the file manually

The template feature would be useful here to include a few shots examples in the prompt to make a small local model to be able to output correctly only the comments block

**Comment by nvms** [comment]
Hello again @synw, sorry for the delay. I've been considering everything we've talked about over the past couple of months and went away for a while to essentially rebuild this extension from scratch, hoping to include everything we've covered as a feature.

The new version was released today. I hope you'll give it a try and find it suits your needs. It includes more control over insertion method (i.e. what happens after generation), that I believe will help you with exactly this.
