### ISSUE TITLE
A new theme sharing

### ISSUE THREAD

**Issue by czkoko** [nvms/wingman#25]
Thanks to nvms for writing such a concise and practical plug-in, I'm just an amateur programmer and can't make a big contribution to your project.

- In order to try another new theme color matching style, If someone like it, just download the attachment below to replace it.
[media.zip](https://github.com/nvms/wingman/files/12792022/media.zip)
<img width="593" alt="2023-10-03 18 54 15" src="https://github.com/nvms/wingman/assets/90698189/3a9370b2-bce2-48fd-bef7-b65f7b7bcdb5">

- After adding special prompts to llama2, it can work perfectly with LM Studio.

- The timeout parameter seems to be unnecessary on the local server, and the openai timeout reminder will keep popping up.
- 
I have made the following modifications and added the judgment of whether the message has been received to automatically complete a single conversation.
```js
      const response = await this.instance!.sendMessage(message, {
        onProgress: (partialResponse: ChatMessage) => {
          if (!parentMessageId) {
              parentMessageId = partialResponse.parentMessageId;
          }
         // Determine whether the message has been received.
          if (partialResponse.detail?.choices[0].finish_reason == "stop") {
              SecondaryViewProvider?.postMessage({ type: "aborted" });
              return
          }
          this.viewProvider?.postMessage({ type: "partialResponse", value: partialResponse });
        },
        systemMessage,
        abortSignal: this._abort.signal,
        ...this.conversationState,
      });
```

**Comment by nvms** [comment]
Thanks for the issue, and sorry for the delay. I've been busy working on the next major release of Wingman, which is available now.

Since this new version includes an entirely new UI, I'll be closing this issue. PRs are always welcome if you'd like to introduce some small theming capabilities. I'm not opposed to enabling theme configuration for small things like syntax highlighting, etc.
