### ISSUE TITLE
Please include the julia language (.jl) extension also. 

### ISSUE THREAD

**Issue by MrBenzWorld** [nvms/wingman#26]
It is excellent, Thank you. Please enable the right click chat option . Please include the julia language (.jl) extension also.  Also please include Julia docs (1.9.3 version) in help for reference. Because, mostly all llama are trained on julia 1.6 version from 2021 data.  But it changed a lot in recent months.

**Comment by nvms** [comment]
Thanks for the issue, and sorry for the delay. I've been busy working on the next major release of Wingman, which is available now. This feature has been included in the release, so I'll be closing this issue as completed.
