### ISSUE TITLE
Wingman v2.0.8 , Local model is not supporting

### ISSUE THREAD

**Issue by NK-Aero** [nvms/wingman#27]
Wingman v2.0.8 , Local model is not supporting. LM Studio, Koboldcpp URL are not working, please provide documentation or tutorial or video about enabling local models. Thank you

**Comment by nvms** [comment]
I'm unfamiliar with LM Studio, but I just downloaded it and started a local inference server running `llama 2 chat 7B q4_0 ggml`. Using the OpenAI provider in Wingman, I changed the URL to `http://localhost:1234/v1/chat/completions` and things seem to just work (with the exception of recognizing the end of the completion stream, which may just be unique to LM Studio, but a bug none-the-less).

Can you provide some more information regarding your setup?

KoboldCpp support is almost finished - still porting this functionality from the previous major version.

![Screenshot 2023-12-04 at 2 01 28 PM](https://github.com/nvms/wingman/assets/17074357/15cd2887-4c19-4d13-a733-ec7eab6be9e9)
